#!/bin/bash
# build-apk.sh — manual APK build for the Inward Journey TV launcher.
#
# Why manual: the Gradle daemon cannot talk to its client in this environment
# (client<->daemon socket fails with "Unexpected type tag"), so Gradle builds
# don't run here. The project has zero dependencies, so a direct
# kotlinc + aapt2 + d8 + apksigner pipeline is simple and deterministic.
#
# Toolchain (installed once, under ~):
#   ~/jdk                       Temurin 17
#   ~/android-sdk               cmdline-tools + platform-34 + build-tools 34.0.0
#   ~/kotlin                    Kotlin compiler 1.9.24
#   ~/.android-debug.keystore   debug signing key (alias androiddebugkey, pw android)
#
# Usage: ./build-apk.sh
# Output: dist/inward-journey-tv.apk

set -e
cd "$(dirname "$0")"

export PATH="$HOME/jdk/bin:$PATH"
SDK="/opt/android-sdk"
BT="$SDK/build-tools/34.0.0"
KCP="$(echo /usr/share/gradle-8.8/lib/*.jar | tr ' ' ':')"
STDLIB="/usr/share/gradle-8.8/lib/kotlin-stdlib-1.9.22.jar"

WORK="$(pwd)/manual-build"
OUT="$WORK/out"
DIST="$(pwd)/dist"
rm -rf "$OUT" "$DIST"
mkdir -p "$OUT/classes" "$OUT/dex" "$DIST"

# Single source of truth for the version: app/build.gradle.
VERSION_CODE="$(sed -n 's/^[[:space:]]*versionCode[[:space:]]\+\([0-9][0-9]*\).*/\1/p' app/build.gradle | head -1)"
VERSION_NAME="$(sed -n 's/^[[:space:]]*versionName[[:space:]]*"\(.*\)".*/\1/p' app/build.gradle | head -1)"
if [ -z "$VERSION_CODE" ] || [ -z "$VERSION_NAME" ]; then
  echo "ERROR: could not parse versionCode/versionName from app/build.gradle" >&2
  exit 1
fi
echo "== version: $VERSION_NAME (code $VERSION_CODE) =="

# Generate the BuildConfig stub AGP would normally produce.
mkdir -p "$WORK/app/inwardjourney/tv"
cat > "$WORK/app/inwardjourney/tv/BuildConfig.java" <<EOF
package app.inwardjourney.tv;
/** Generated by build-apk.sh from app/build.gradle (manual-build AGP stand-in). */
public final class BuildConfig {
    public static final boolean DEBUG = true;
    public static final int VERSION_CODE = $VERSION_CODE;
    public static final String VERSION_NAME = "$VERSION_NAME";
}
EOF

echo "== 1. kotlinc =="
java -cp "$KCP" org.jetbrains.kotlin.cli.jvm.K2JVMCompiler \
  app/src/main/java/app/inwardjourney/tv/LauncherActivity.kt \
  app/src/main/java/app/inwardjourney/tv/PlayerActivity.kt \
  app/src/main/java/app/inwardjourney/tv/GameUpdater.kt \
  app/src/main/java/app/inwardjourney/tv/LauncherUpdate.kt \
  "$WORK/app/inwardjourney/tv/BuildConfig.java" \
  -classpath "$SDK/platforms/android-34/android.jar:$STDLIB" \
  -d "$OUT/classes" -jvm-target 17 -no-stdlib

echo "== 2. aapt2 compile =="
"$BT/aapt2" compile --dir app/src/main/res -o "$OUT/res.zip"

echo "== 3. aapt2 link =="
"$BT/aapt2" link -o "$OUT/base.apk" \
  -I "$SDK/platforms/android-34/android.jar" \
  --manifest "$WORK/AndroidManifest.xml" \
  --min-sdk-version 28 --target-sdk-version 34 \
  --version-code "$VERSION_CODE" --version-name "$VERSION_NAME" \
  "$OUT/res.zip"

echo "== 4. d8 =="
"$BT/d8" --lib "$SDK/platforms/android-34/android.jar" \
  --min-api 28 --output "$OUT/dex" \
  $(find "$OUT/classes" -name "*.class") \
  "$STDLIB"

echo "== 5. add classes.dex (stored, uncompressed) =="
cp "$OUT/base.apk" "$OUT/unaligned.apk"
(cd "$OUT/dex" && zip -q -0 ../unaligned.apk classes.dex)

echo "== 6. zipalign =="
"$BT/zipalign" -f 4 "$OUT/unaligned.apk" "$OUT/aligned.apk"

echo "== 7. apksigner =="
"$BT/apksigner" sign \
  --ks "$HOME/.android-debug.keystore" --ks-pass pass:android --key-pass pass:android \
  --out "$DIST/inward-journey-tv.apk" "$OUT/aligned.apk"
"$BT/apksigner" verify --print-certs "$DIST/inward-journey-tv.apk" | head -3

echo "== APK: $DIST/inward-journey-tv.apk ($(stat -c%s "$DIST/inward-journey-tv.apk") bytes) =="
